### ISSUE TITLE
Missing local.properties.

### ISSUE THREAD

**Issue by Borwe** [ElarianLtd/java-sdk#3]
https://github.com/ElarianLtd/java-sdk/blob/a4a603c1d2bb6e60bb182be5550fd11ee570d302/build.gradle#L1-L7

Tried to compile on PC and got missing "local.properties" error, I think you forgot to add it or something.

**Comment by aksalj** [comment]
Hey @Borwe, if you're doing local development of the SDK, you need to create your own properties file. We do not commit `local.properties` because it contains info specific to our local environment.

However, if you're trying to use the SDK, you don't need to compile it locally, just add it as a dependency to your project.
